#!/bin/bash

# Path to Xilinx tools on the host. Override with: VIVADO_DIR=/your/path ./Build_Matador
VIVADO_DIR=${VIVADO_DIR:-/tools/Xilinx}

# X11 auth file. Override with: XAUTH=/your/path ./Build_Matador
XAUTH=${XAUTH:-$XAUTHORITY}

docker build -t matador_docker:v1 .
docker run -it \
    --security-opt label=type:container_runtime_t \
    --network=host \
    -e DISPLAY="$DISPLAY" \
    -v "${VIVADO_DIR}:${VIVADO_DIR}" \
    -v "$(pwd):/app" \
    -v "${XAUTH}:/root/.Xauthority:rw" \
    matador_docker:v1
