#!/bin/bash

docker build -t matador_docker:v1 .
docker run -it --security-opt label=type:container_runtime_t --network=host -e DISPLAY=$DISPLAY -v /tools/Xilinx/Vivado/2022.2/:/tools/Xilinx/Vivado/2022.2/ -v /home/tousif/Desktop/Matador_Docker/:/home/tousif/Desktop/Matador_Docker/ -v "/run/user/1000/gdm/Xauthority:/root/.Xauthority:rw" matador_docker:v1