site_name: Matador
site_description: Automated RTL accelerator generator for Tsetlin Machines
site_url: https://nclaes.github.io/matador/
repo_url: https://github.com/nclaes/matador
repo_name: nclaes/matador
edit_uri: edit/production_ready/docs/

docs_dir: docs

theme:
  name: material
  logo: assets/img/icon.png
  favicon: assets/img/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - content.code.copy
    - content.action.edit

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup: Setup.md
  - Usage: Usage.md
  - Generated Outputs: GeneratedOutputs.md
  - Developer Guide: Developer.md
  - TMIR Spec: tmir_spec.md
