[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "matador"
version = "0.2.0-dev0"
requires-python = ">=3.10"
dependencies = [
    "jinja2",
    "pyyaml",
    "pydantic>=2",
    "click",
    "numpy",
    "setuptools",
    "cffi>=1.0",
    "scipy",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "ruff",
    "black",
    "pre-commit",
    "mypy",
]

[project.scripts]
matador = "matador.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["matador*", "tmu*"]
