"""Generate a self-contained ROM-inference provenance script.

Auto-called after export_tmir() and (optionally) after RTL generation.
Writes three files into the output directory:

  rom_inference.py      — standalone Python script (numpy-only, no matador)
  ta_actions.npy        — Include-action bool array  (n_classes, n_cpc, n_literals)
  model_metadata.json   — parameters needed by the script

The generated script accepts either ta_actions.npy or tm_accelerator.v
as its --model input, so a collaborator can verify inference from the
raw ROM data without installing matador.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from matador.ir.tm_ir import TMIR


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_provenance_artifacts(tmir: "TMIR", out_dir: Path, test_data_path: Path | None = None) -> Path:
    """Write ta_actions.npy, model_metadata.json, and rom_inference.py into out_dir.

    Args:
        tmir:            Loaded TMIR (must have passed validate_self()).
        out_dir:         Directory to write into (created if absent).
        test_data_path:  Embedded as the default --test-data in the script.

    Returns:
        Path to the generated rom_inference.py.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    # Materialise includes (threshold ta_states if needed)
    tmir.to_includes()
    arch = tmir.architecture
    hyper = tmir.hyperparameters
    prov = tmir.provenance

    includes = tmir.representation.includes.astype(bool)  # type: ignore[union-attr]

    # Reshape to (n_classes, n_cpc, n_literals) regardless of storage shape
    n_cpc = arch.n_clauses_per_class or arch.n_clauses_total
    includes_3d = includes.reshape(arch.n_classes, n_cpc, arch.n_literals)

    # ── ta_actions.npy ────────────────────────────────────────────────────────
    npy_path = out_dir / "ta_actions.npy"
    np.save(str(npy_path), includes_3d)

    # ── model_metadata.json ──────────────────────────────────────────────────
    meta = {
        "n_features":          arch.n_features,
        "n_literals":          arch.n_literals,
        "n_classes":           arch.n_classes,
        "n_clauses_total":     arch.n_clauses_total,
        "n_clauses_per_class": n_cpc,
        "model_fingerprint":   tmir.fingerprint(),
        "model_variant":       tmir.variant,
        "hyperparameters": {
            "s":        hyper.s,
            "T":        arch.threshold,
            "n_states": hyper.n_states,
            "seed":     hyper.seed,
        },
        "provenance": {
            "trained_at":        prov.trained_at.isoformat() if prov else None,
            "epochs":            prov.epochs if prov else None,
            "framework":         prov.framework if prov else None,
            "framework_version": prov.framework_version if prov else None,
        },
    }
    meta_path = out_dir / "model_metadata.json"
    meta_path.write_text(json.dumps(meta, indent=2, default=str))

    # ── rom_inference.py ──────────────────────────────────────────────────────
    default_test = str(test_data_path.resolve()) if test_data_path else ""
    fingerprint  = tmir.fingerprint()
    script = _render_script(default_test, fingerprint)
    script_path = out_dir / "rom_inference.py"
    script_path.write_text(script)
    script_path.chmod(0o755)

    return script_path


# ---------------------------------------------------------------------------
# Script template
# ---------------------------------------------------------------------------

def _render_script(default_test_data: str, model_fingerprint: str = "") -> str:
    return f'''\
#!/usr/bin/env python3
"""ROM-based inference provenance script — auto-generated by Matador.

Loads the Tsetlin Machine Include-action matrix from either:
  - ta_actions.npy     (companion file written by matador train)
  - tm_accelerator.v   (the synthesisable Verilog ROM — parsed directly)

Runs the full test dataset through a pure-NumPy inference engine that
implements the identical algorithm to the RTL.  Produces a JSON report
with accuracy, per-class breakdown, confusion matrix, model fingerprint,
and dataset SHA-256.

Requirements: Python >= 3.8, numpy.  No matador installation needed.

Usage
-----
  # From ta_actions.npy (simplest):
  python3 rom_inference.py --test-data /path/to/test.txt

  # Explicit model path:
  python3 rom_inference.py --model ta_actions.npy --test-data /path/to/test.txt

  # Directly from Verilog ROM:
  python3 rom_inference.py --model ../RTL/src/tm_accelerator.v --test-data /path/to/test.txt

  # Write report to a specific file:
  python3 rom_inference.py --test-data /path/to/test.txt --output report.json

Reproducibility
---------------
Two values in the report tie everything together:

  model_fingerprint — SHA-256 over the canonical model definition
    (architecture + hyperparameters + Include-action matrix).
    The RTL is synthesised from the same Include-action matrix that
    this script reads.  Anyone who recomputes the fingerprint from
    ta_actions.npy or by parsing tm_accelerator.v can confirm they
    are running against the identical weights — not a different
    training run or an accidentally modified file.  In a fault
    injection study this locks down the fault-free baseline: the
    reported accuracy is only meaningful if the fingerprint matches
    the one used to generate the bitstream under test.

    This model was generated with fingerprint:
      {model_fingerprint}

  test_data_sha256 — SHA-256 of the raw test dataset file.
    Test accuracy is only comparable across experiments when every
    party uses the same samples in the same order.  The hash commits
    to the exact byte content of the file: the binarisation method,
    the feature values, the class labels, and the sample count.
    Verify with:  sha256sum <test_data_file>
    If the hash differs from the value in this report, the accuracy
    numbers cannot be directly compared.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

def load_from_npy(npy_path: Path):
    """Load includes from ta_actions.npy.

    Returns (includes, meta) where:
      includes: bool array, shape (n_classes, n_cpc, n_literals)
      meta:     dict from model_metadata.json (or empty dict if absent)
    """
    includes = np.load(str(npy_path)).astype(bool)
    meta_path = npy_path.parent / "model_metadata.json"
    meta = json.loads(meta_path.read_text()) if meta_path.exists() else {{}}
    return includes, meta


def load_from_verilog(v_path: Path):
    """Parse a Matador-generated tm_accelerator.v and recover the Include-action matrix.

    The ROM init block has the form:
        tile_rom[<addr>] = <TW>\\'h<hex>;  // feat_slice=<fi> clause_slice=<ci>

    Tile layout per entry at (fi, ci):
        bits [ k*2*FEAT_SLICE         +: FEAT_SLICE ] = positive Include actions, clause k
        bits [ k*2*FEAT_SLICE+FEAT_SLICE +: FEAT_SLICE ] = negated  Include actions, clause k
    where k = 0 .. CLAUSE_SLICE-1 within this tile and clause k+ci*CLAUSE_SLICE globally.

    Returns (includes, meta) where:
      includes: bool array, shape (n_classes, n_cpc, n_literals)
      meta:     dict of extracted parameters
    """
    text = v_path.read_text()

    # Parse module parameters
    params = {{}}
    for m in re.finditer(r"parameter\\s+(\\w+)\\s*=\\s*(\\d+)", text):
        params[m.group(1)] = int(m.group(2))

    required = ["N_FEATURES", "N_CLASSES", "N_CLAUSES_PC", "N_CLAUSES_TOTAL",
                "FEAT_SLICE", "CLAUSE_SLICE", "N_FEAT_SLICES", "N_CLAUSE_SLICES"]
    missing = [k for k in required if k not in params]
    if missing:
        raise ValueError(
            f"Could not find parameters in {{v_path.name}}: {{missing}}\\n"
            "Make sure the file is a Matador-generated tm_accelerator.v."
        )

    N   = params["N_FEATURES"]
    C   = params["N_CLASSES"]
    K   = params["N_CLAUSES_PC"]
    CT  = params["N_CLAUSES_TOTAL"]
    FS  = params["FEAT_SLICE"]
    CS  = params["CLAUSE_SLICE"]

    # Reconstruct ta_actions (n_clauses_total, 2*n_features)
    ta_actions = np.zeros((CT, 2 * N), dtype=bool)

    rom_re = re.compile(
        r"tile_rom\\[\\s*(\\d+)\\s*\\]\\s*=\\s*\\d+\\'h([0-9A-Fa-f]+);"
        r"[^\\n]*feat_slice=(\\d+)\\s+clause_slice=(\\d+)"
    )
    for m in rom_re.finditer(text):
        fi       = int(m.group(3))
        ci       = int(m.group(4))
        tile_val = int(m.group(2), 16)

        for k in range(CS):
            g = ci * CS + k           # global clause index
            if g >= CT:
                continue
            for l_local in range(FS):
                feat_global = fi * FS + l_local
                if feat_global >= N:
                    continue
                pos_bit = k * 2 * FS + l_local
                neg_bit = k * 2 * FS + FS + l_local
                if (tile_val >> pos_bit) & 1:
                    ta_actions[g, feat_global] = True
                if (tile_val >> neg_bit) & 1:
                    ta_actions[g, N + feat_global] = True

    includes = ta_actions.reshape(C, K, 2 * N)

    meta = {{
        "n_features":          N,
        "n_literals":          2 * N,
        "n_classes":           C,
        "n_clauses_total":     CT,
        "n_clauses_per_class": K,
        "model_fingerprint":   "N/A (parsed from Verilog)",
        "model_variant":       "vanilla",
        "hyperparameters":     {{k: params.get(k) for k in
                               ["N_FEATURES", "N_CLASSES", "N_CLAUSES_PC", "N_CLAUSES_TOTAL"]}},
    }}

    # Try to load companion metadata if available
    meta_path = v_path.parent.parent / "TMIR" / "model_metadata.json"
    if not meta_path.exists():
        meta_path = v_path.parent / "model_metadata.json"
    if meta_path.exists():
        companion = json.loads(meta_path.read_text())
        meta["model_fingerprint"] = companion.get("model_fingerprint", meta["model_fingerprint"])
        meta["hyperparameters"]   = companion.get("hyperparameters", meta["hyperparameters"])
        meta["provenance"]        = companion.get("provenance", {{}})

    return includes, meta


# ---------------------------------------------------------------------------
# Inference — identical algorithm to the RTL
# ---------------------------------------------------------------------------

def predict(includes: np.ndarray, X: np.ndarray):
    """Run TM inference from the Include-action matrix.

    Args:
        includes: bool, shape (n_classes, n_clauses_per_class, n_literals)
        X:        uint8 0/1, shape (n_samples, n_features)

    Returns:
        predictions: (n_samples,) int64
        scores:      (n_samples, n_classes) int64

    Convention: a clause with ZERO included literals outputs 0 at inference
    (matches RTL behaviour; differs from TMU training where empty clauses
    output 1 so the regulator can shrink them).
    """
    n_classes, n_cpc, n_literals = includes.shape
    n_samples, n_features = X.shape

    # Build literal matrix: [x_0 ... x_F-1, ~x_0 ... ~x_F-1]
    L = np.empty((n_samples, 2 * n_features), dtype=np.uint8)
    L[:, :n_features] = X
    L[:, n_features:] = 1 - X

    half     = n_cpc // 2
    polarity = np.where(np.arange(n_cpc) < half, 1, -1)   # (n_cpc,)

    # Flatten includes for batch computation
    flat_inc = includes.reshape(-1, n_literals)             # (n_classes*n_cpc, n_literals)
    n_total  = flat_inc.shape[0]

    flat_out = np.zeros((n_samples, n_total), dtype=np.int8)
    for k in range(n_total):
        mask = flat_inc[k]
        if not mask.any():
            continue                                        # empty clause → 0
        flat_out[:, k] = L[:, mask].all(axis=1).astype(np.int8)

    # co: (n_samples, n_classes, n_cpc)
    co     = flat_out.reshape(n_samples, n_classes, n_cpc)
    scores = (co * polarity[np.newaxis, np.newaxis, :]).sum(axis=2)
    preds  = np.argmax(scores, axis=1)
    return preds.astype(np.int64), scores.astype(np.int64)


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def build_report(includes, meta, test_data_path: Path, model_source: str):
    raw    = np.genfromtxt(str(test_data_path), delimiter=" ", dtype=np.uint32)
    X_test = raw[:, :-1].astype(np.uint8)
    y_test = raw[:, -1].astype(np.int64)

    data_sha256 = hashlib.sha256(test_data_path.read_bytes()).hexdigest()

    preds, scores = predict(includes, X_test)
    correct_mask  = preds == y_test
    n_correct     = int(correct_mask.sum())
    n_total       = len(y_test)
    accuracy_pct  = round(100.0 * n_correct / n_total, 4) if n_total else 0.0

    n_classes = includes.shape[0]
    classes   = sorted(int(c) for c in np.unique(y_test))
    per_class = {{}}
    for cls in classes:
        mask        = y_test == cls
        cls_total   = int(mask.sum())
        cls_correct = int((correct_mask & mask).sum())
        per_class[str(cls)] = {{
            "correct":      cls_correct,
            "total":        cls_total,
            "accuracy_pct": round(100.0 * cls_correct / cls_total, 4) if cls_total else 0.0,
        }}

    cm = np.zeros((n_classes, n_classes), dtype=np.int64)
    for t, p in zip(y_test, preds):
        if 0 <= int(t) < n_classes and 0 <= int(p) < n_classes:
            cm[int(t), int(p)] += 1

    report = {{
        "generated_at":       datetime.now(timezone.utc).isoformat(),
        "python_version":     platform.python_version(),
        "platform":           platform.platform(),
        "model_source":       model_source,
        "model_fingerprint":  meta.get("model_fingerprint", ""),
        "model_variant":      meta.get("model_variant", ""),
        "n_features":         meta.get("n_features", includes.shape[2] // 2),
        "n_classes":          meta.get("n_classes", includes.shape[0]),
        "n_clauses_total":    meta.get("n_clauses_total", includes.shape[0] * includes.shape[1]),
        "n_clauses_per_class":meta.get("n_clauses_per_class", includes.shape[1]),
        "hyperparameters":    meta.get("hyperparameters", {{}}),
        "provenance":         meta.get("provenance", {{}}),
        "test_data_path":     str(test_data_path.resolve()),
        "test_data_sha256":   data_sha256,
        "n_samples":          n_total,
        "inference_engine":   "Pure NumPy — ROM-equivalent (Include-action matrix, no tmu dependency)",
        "accuracy_pct":       accuracy_pct,
        "accuracy_correct":   n_correct,
        "accuracy_total":     n_total,
        "per_class":          per_class,
        "confusion_matrix":   cm.tolist(),
    }}
    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    here = Path(__file__).parent

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--model", default=str(here / "ta_actions.npy"),
        help="ta_actions.npy or tm_accelerator.v  (default: ta_actions.npy alongside this script)",
    )
    parser.add_argument(
        "--test-data", default={repr(default_test_data)},
        help="Space-separated Boolean test dataset (last column = class label)",
    )
    parser.add_argument(
        "--output", default=str(here / "provenance_report.json"),
        help="Output JSON report path  (default: provenance_report.json alongside this script)",
    )
    args = parser.parse_args()

    model_path    = Path(args.model)
    test_data_path = Path(args.test_data)
    output_path   = Path(args.output)

    if not model_path.exists():
        print(f"ERROR: model file not found: {{model_path}}", file=sys.stderr)
        sys.exit(1)
    if not test_data_path.exists():
        print(f"ERROR: test dataset not found: {{test_data_path}}", file=sys.stderr)
        sys.exit(1)

    # Load
    suffix = model_path.suffix.lower()
    if suffix == ".v":
        print(f"Loading Include-action matrix from Verilog ROM: {{model_path.name}}")
        includes, meta = load_from_verilog(model_path)
    else:
        print(f"Loading Include-action matrix from: {{model_path.name}}")
        includes, meta = load_from_npy(model_path)

    print(f"  {{includes.shape[0]}} classes  |  {{includes.shape[1]}} clauses/class  "
          f"|  {{includes.shape[2]//2}} features")
    print(f"  Non-zero literals: {{includes.sum()}}  /  {{includes.size}}  "
          f"({{100*includes.mean():.1f}}% include rate)")
    print()
    print(f"Running inference on: {{test_data_path.name}}")

    report = build_report(includes, meta, test_data_path, str(model_path.resolve()))

    print(f"  Accuracy : {{report['accuracy_pct']:.2f}}%"
          f"  ({{report['accuracy_correct']}}/{{report['accuracy_total']}})")
    print()
    print("  Per-class accuracy:")
    for cls, res in report["per_class"].items():
        print(f"    class {{cls:>2}}  {{res['accuracy_pct']:6.2f}}%"
              f"  ({{res['correct']}}/{{res['total']}})")
    print()
    print(f"  Model fingerprint : {{report['model_fingerprint']}}")
    print(f"  Dataset SHA-256   : {{report['test_data_sha256']}}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, default=str))
    print()
    print(f"Report written to: {{output_path}}")


if __name__ == "__main__":
    main()
'''
