"""Generate a self-contained ROM-inference provenance script.

Auto-called after export_tmir() and (optionally) after RTL generation.
Writes three files into the output directory:

  rom_inference.py      — standalone Python script (numpy-only, no matador)
  ta_actions.npy        — Include-action bool array  (n_classes, n_cpc, n_literals)
  model_metadata.json   — parameters needed by the script

The generated script accepts either ta_actions.npy or tm_accelerator.v
as its --model input, so a collaborator can verify inference from the
raw ROM data without installing matador.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from matador.ir.tm_ir import TMIR


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_provenance_artifacts(tmir: "TMIR", out_dir: Path, test_data_path: Path | None = None) -> Path:
    """Write ta_actions.npy, model_metadata.json, and rom_inference.py into out_dir.

    Args:
        tmir:            Loaded TMIR (must have passed validate_self()).
        out_dir:         Directory to write into (created if absent).
        test_data_path:  Embedded as the default --test-data in the script.

    Returns:
        Path to the generated rom_inference.py.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    # Materialise includes (threshold ta_states if needed)
    tmir.to_includes()
    arch = tmir.architecture
    hyper = tmir.hyperparameters
    prov = tmir.provenance

    includes = tmir.representation.includes.astype(bool)  # type: ignore[union-attr]

    # Reshape to (n_classes, n_cpc, n_literals) regardless of storage shape
    n_cpc = arch.n_clauses_per_class or arch.n_clauses_total
    includes_3d = includes.reshape(arch.n_classes, n_cpc, arch.n_literals)

    # ── ta_actions.npy ────────────────────────────────────────────────────────
    npy_path = out_dir / "ta_actions.npy"
    np.save(str(npy_path), includes_3d)

    # ── model_metadata.json ──────────────────────────────────────────────────
    meta = {
        "n_features":          arch.n_features,
        "n_literals":          arch.n_literals,
        "n_classes":           arch.n_classes,
        "n_clauses_total":     arch.n_clauses_total,
        "n_clauses_per_class": n_cpc,
        "model_fingerprint":   tmir.fingerprint(),
        "model_variant":       tmir.variant,
        "hyperparameters": {
            "s":        hyper.s,
            "T":        arch.threshold,
            "n_states": hyper.n_states,
            "seed":     hyper.seed,
        },
        "provenance": {
            "trained_at":        prov.trained_at.isoformat() if prov else None,
            "epochs":            prov.epochs if prov else None,
            "framework":         prov.framework if prov else None,
            "framework_version": prov.framework_version if prov else None,
        },
    }
    meta_path = out_dir / "model_metadata.json"
    meta_path.write_text(json.dumps(meta, indent=2, default=str))

    # ── rom_inference.py ──────────────────────────────────────────────────────
    default_test = str(test_data_path.resolve()) if test_data_path else ""
    fingerprint  = tmir.fingerprint()
    script = _render_script(default_test, fingerprint)
    script_path = out_dir / "rom_inference.py"
    script_path.write_text(script)
    script_path.chmod(0o755)

    return script_path


# ---------------------------------------------------------------------------
# Script template
# ---------------------------------------------------------------------------

def _render_script(default_test_data: str, model_fingerprint: str = "") -> str:
    return f'''\
#!/usr/bin/env python3
"""ROM-based inference provenance script — auto-generated by Matador.

PURPOSE
-------
This script lets anyone verify that a trained Tsetlin Machine (TM) model
produces the same predictions as the hardware RTL, without needing the
Matador installation, the tmu training library, or a simulator.

It reads the trained model's Include-action matrix and runs the same
inference algorithm that the synthesised RTL implements.  The result is
a JSON provenance report showing accuracy, per-class breakdown, confusion
matrix, and two fingerprints that lock down exactly which model and dataset
were used.

Requirements: Python 3.8+, numpy.  Nothing else.

WHAT IS THE INCLUDE-ACTION MATRIX?
-----------------------------------
A Tsetlin Machine learns by adjusting Tsetlin Automata (TAs) — one per
literal per clause.  After training, each TA has settled into one of two
actions: Include (the literal matters to this clause) or Exclude (ignore it).

The Include-action matrix is a 3-D boolean array:

  shape: (n_classes, n_clauses_per_class, n_literals)

  includes[class][clause][literal] = True  →  this literal is tested
  includes[class][clause][literal] = False →  this literal is ignored

There are 2 × n_features literals: first the positive features (x_0 … x_F-1),
then the negated features (~x_0 … ~x_F-1).

This matrix is the ONLY thing stored in the tile ROM on the FPGA.
Everything else (scoring, argmax) is combinational logic.

HOW INFERENCE WORKS (plain English)
-------------------------------------
For each input sample:

  1. Build the literal vector: [x_0, x_1, …, x_F-1, ~x_0, ~x_1, …, ~x_F-1]
     (positive features followed by their complements)

  2. For each clause, check whether all its included literals are satisfied:
       clause fires = AND over all literals where includes[c][k][l] is True
       If a clause has NO included literals it outputs 0 (never fires).

  3. Accumulate scores per class:
       score[c] = Σ(positive clauses that fire) − Σ(negative clauses that fire)
       The first half of each class's clauses are positive; the second half negative.

  4. Predict the class with the highest score.

This is exactly what the RTL does across its FSM states.

USAGE
-----
  # Simplest — use ta_actions.npy alongside this script:
  python3 rom_inference.py --test-data /path/to/test.txt

  # Load from a specific .npy file:
  python3 rom_inference.py --model ta_actions.npy --test-data /path/to/test.txt

  # Parse the Verilog ROM directly (no .npy needed):
  python3 rom_inference.py --model ../RTL/src/tm_accelerator.v --test-data /path/to/test.txt

  # Specify where to write the report:
  python3 rom_inference.py --test-data /path/to/test.txt --output report.json

REPRODUCIBILITY
---------------
Two values in the report pin down exactly what was tested.

  model_fingerprint
    A SHA-256 hash of the complete model definition (architecture,
    hyperparameters, and every bit of the Include-action matrix).
    If two runs produce the same fingerprint, they used identical weights.
    Use this to confirm the script is running against the same model that
    was synthesised onto the FPGA — not a different training run or a
    file that was accidentally modified.

    This model:  {model_fingerprint}

  test_data_sha256
    A SHA-256 hash of the raw test dataset file.
    Accuracy numbers are only comparable when every party uses the exact
    same samples in the same order.  Verify with:
      sha256sum <your_test_file>
    If the hash differs from the one in this report, the accuracy figures
    cannot be directly compared.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np


# ---------------------------------------------------------------------------
# Step 1 — Load the Include-action matrix
# ---------------------------------------------------------------------------

def load_from_npy(npy_path: Path):
    """Load the Include-action matrix from the ta_actions.npy companion file.

    ta_actions.npy is a 3-D boolean numpy array written by 'matador train':
      shape: (n_classes, n_clauses_per_class, n_literals)
      dtype: bool
      True  = TA issued Include  (this literal is tested by this clause)
      False = TA issued Exclude  (this literal is ignored by this clause)

    n_literals = 2 × n_features:
      first  n_features positions → positive literals (x_0, x_1, …, x_F-1)
      second n_features positions → negated  literals (~x_0, ~x_1, …, ~x_F-1)

    Returns:
      include_matrix : bool array, shape (n_classes, n_clauses_per_class, n_literals)
      meta           : dict with model parameters (from model_metadata.json if present)
    """
    include_matrix = np.load(str(npy_path)).astype(bool)
    meta_path = npy_path.parent / "model_metadata.json"
    meta = json.loads(meta_path.read_text()) if meta_path.exists() else {{}}
    return include_matrix, meta


def load_from_verilog(v_path: Path):
    """Reconstruct the Include-action matrix by parsing the synthesised Verilog ROM.

    Background — how the tile ROM is structured
    --------------------------------------------
    Matador's tiled accelerator stores the Include-action matrix in a 2-D ROM
    indexed by (feat_slice, clause_slice).  Each ROM entry covers a rectangular
    tile of the full (features × clauses) matrix:

      tile_rom[feat_slice * N_CLAUSE_SLICES + clause_slice] = <hex value>
      comment:  // feat_slice=<fi>  clause_slice=<ci>

    Within a tile of width TILE_WIDTH = CLAUSE_SLICE × 2 × FEAT_SLICE bits:

      For each clause k (0 … CLAUSE_SLICE-1) within this tile:
        Global clause index:  g = clause_slice × CLAUSE_SLICE + k

        Positive Include bits for features [fi×FS … (fi+1)×FS - 1]:
          bit position in tile = k × 2 × FEAT_SLICE + l_local

        Negated Include bits for those same features:
          bit position in tile = k × 2 × FEAT_SLICE + FEAT_SLICE + l_local

        where l_local = 0 … FEAT_SLICE-1 (local feature index within the tile column)
        and   feat_global = fi × FEAT_SLICE + l_local (global feature index)

    Redundant (padding) entries
    ---------------------------
    The ROM dimensions are ceiling-divided:
      N_FEAT_SLICES   = ceil(N_FEATURES   / FEAT_SLICE)
      N_CLAUSE_SLICES = ceil(N_CLAUSES_TOTAL / CLAUSE_SLICE)

    So the last feature slice may contain padding feature positions
    (feat_global >= N_FEATURES), and the last clause slice may contain
    padding clause positions (g >= N_CLAUSES_TOTAL).  Both are written
    as zero bits in the ROM.  This function skips them so the recovered
    matrix has exactly N_CLAUSES_TOTAL rows and 2 × N_FEATURES columns —
    no phantom clauses or features are introduced.

    Returns:
      include_matrix : bool array, shape (n_classes, n_clauses_per_class, n_literals)
      meta           : dict with model parameters extracted from the file
    """
    text = v_path.read_text()

    # ── Read model dimensions from the Verilog parameter declarations ──────
    params = {{}}
    for m in re.finditer(r"parameter\\s+(\\w+)\\s*=\\s*(\\d+)", text):
        params[m.group(1)] = int(m.group(2))

    required = ["N_FEATURES", "N_CLASSES", "N_CLAUSES_PC", "N_CLAUSES_TOTAL",
                "FEAT_SLICE", "CLAUSE_SLICE", "N_FEAT_SLICES", "N_CLAUSE_SLICES"]
    missing = [k for k in required if k not in params]
    if missing:
        raise ValueError(
            f"Could not find parameters in {{v_path.name}}: {{missing}}\\n"
            "Make sure the file is a Matador-generated tm_accelerator.v."
        )

    N  = params["N_FEATURES"]       # number of input features
    C  = params["N_CLASSES"]        # number of output classes
    K  = params["N_CLAUSES_PC"]     # clauses per class
    CT = params["N_CLAUSES_TOTAL"]  # = C × K
    FS = params["FEAT_SLICE"]       # feature slice width (tile columns)
    CS = params["CLAUSE_SLICE"]     # clause slice width  (tile rows)

    # ── Allocate the flat Include-action table ─────────────────────────────
    # Rows = one per clause (CT total), columns = one per literal (2 × N).
    # Positive literals occupy columns 0 … N-1, negated literals N … 2N-1.
    include_flat = np.zeros((CT, 2 * N), dtype=bool)

    # ── Parse every tile ROM entry and unpack its bits ─────────────────────
    rom_pattern = re.compile(
        r"tile_rom\\[\\s*(\\d+)\\s*\\]\\s*=\\s*\\d+\\'h([0-9A-Fa-f]+);"
        r"[^\\n]*feat_slice=(\\d+)\\s+clause_slice=(\\d+)"
    )
    for entry in rom_pattern.finditer(text):
        fi       = int(entry.group(3))   # which feature slice column
        ci       = int(entry.group(4))   # which clause slice row
        tile_val = int(entry.group(2), 16)

        for k in range(CS):
            g = ci * CS + k              # global clause index for this slot

            # Skip padding: last clause slice may not be fully used
            if g >= CT:
                continue

            for l_local in range(FS):
                feat_global = fi * FS + l_local   # global feature index

                # Skip padding: last feature slice may not be fully used
                if feat_global >= N:
                    continue

                # Bit positions within the tile entry for this clause/feature
                pos_bit = k * 2 * FS + l_local        # positive literal
                neg_bit = k * 2 * FS + FS + l_local   # negated  literal

                if (tile_val >> pos_bit) & 1:
                    include_flat[g, feat_global] = True          # x[feat_global] included
                if (tile_val >> neg_bit) & 1:
                    include_flat[g, N + feat_global] = True      # ~x[feat_global] included

    # ── Reshape to (n_classes, n_clauses_per_class, n_literals) ───────────
    include_matrix = include_flat.reshape(C, K, 2 * N)

    meta = {{
        "n_features":          N,
        "n_literals":          2 * N,
        "n_classes":           C,
        "n_clauses_total":     CT,
        "n_clauses_per_class": K,
        "model_fingerprint":   "N/A (parsed from Verilog — use ta_actions.npy for fingerprint)",
        "model_variant":       "vanilla",
    }}

    # Supplement with companion metadata.json if it exists nearby
    for candidate in [v_path.parent.parent / "TMIR" / "model_metadata.json",
                      v_path.parent / "model_metadata.json"]:
        if candidate.exists():
            companion = json.loads(candidate.read_text())
            meta["model_fingerprint"] = companion.get("model_fingerprint", meta["model_fingerprint"])
            meta["hyperparameters"]   = companion.get("hyperparameters", {{}})
            meta["provenance"]        = companion.get("provenance", {{}})
            break

    return include_matrix, meta


# ---------------------------------------------------------------------------
# Step 2 — Run inference (identical algorithm to the RTL)
# ---------------------------------------------------------------------------

def run_inference(include_matrix: np.ndarray, features: np.ndarray):
    """Classify a batch of samples using the Include-action matrix.

    This function implements the same three-step algorithm the RTL executes:

    Step A — Build the literal vector
      For each sample, extend the feature vector with its complement:
        literals = [x_0, x_1, …, x_F-1,  ~x_0, ~x_1, …, ~x_F-1]
      The first F positions are the raw feature values (0 or 1).
      The next  F positions are their bitwise negations.

    Step B — Evaluate every clause
      A clause fires (outputs 1) if ALL of its included literals equal 1.
      A clause with no included literals never fires (outputs 0).
      This matches the RTL: an empty clause never contributes to any score.

    Step C — Accumulate per-class scores and take the argmax
      Each class has n_clauses_per_class clauses split into two halves:
        first  half → positive polarity (+1 when it fires)
        second half → negative polarity (-1 when it fires)
      score[c] = Σ(positive clauses that fire) − Σ(negative clauses that fire)
      Predicted class = argmax over scores.

    Args:
      include_matrix : bool, shape (n_classes, n_clauses_per_class, n_literals)
      features       : uint8 0/1, shape (n_samples, n_features)

    Returns:
      predictions : int64, shape (n_samples,)        — predicted class per sample
      scores      : int64, shape (n_samples, n_classes) — raw class scores
    """
    n_classes, n_cpc, n_literals = include_matrix.shape
    n_samples, n_features = features.shape

    # Step A: build literal vector for every sample at once
    literals = np.empty((n_samples, 2 * n_features), dtype=np.uint8)
    literals[:, :n_features] = features          # positive literals
    literals[:, n_features:] = 1 - features      # negated  literals

    # Polarity: +1 for first half of each class's clauses, -1 for second half
    half     = n_cpc // 2
    polarity = np.where(np.arange(n_cpc) < half, 1, -1)

    # Step B: evaluate all clauses in one flat pass for efficiency
    # Flatten to (n_classes × n_cpc, n_literals) so we loop over total clauses
    flat_includes = include_matrix.reshape(-1, n_literals)
    clause_outputs = np.zeros((n_samples, len(flat_includes)), dtype=np.int8)

    for clause_idx, included_literals in enumerate(flat_includes):
        if not included_literals.any():
            # Empty clause: no included literals → always outputs 0
            continue
        # Clause fires if every included literal is 1 in this sample
        clause_outputs[:, clause_idx] = (
            literals[:, included_literals].all(axis=1).astype(np.int8)
        )

    # Step C: reshape back to (n_samples, n_classes, n_cpc) and apply polarity
    clause_outputs = clause_outputs.reshape(n_samples, n_classes, n_cpc)
    scores      = (clause_outputs * polarity[np.newaxis, np.newaxis, :]).sum(axis=2)
    predictions = np.argmax(scores, axis=1)

    return predictions.astype(np.int64), scores.astype(np.int64)


# ---------------------------------------------------------------------------
# Step 3 — Build the provenance report
# ---------------------------------------------------------------------------

def build_provenance_report(include_matrix, meta, test_data_path: Path, model_source: str):
    """Run inference on the full test dataset and compile a provenance report.

    Loads the test data (space-separated Boolean values, last column = class label),
    runs run_inference(), and collects accuracy, per-class breakdown, confusion
    matrix, model fingerprint, and dataset SHA-256 into a dict that can be
    written as JSON.

    You can call run_inference() and this function independently if you want
    to reuse the inference logic without generating the full report.
    """
    # Load test data: each row is a sample, last column is the class label
    raw    = np.genfromtxt(str(test_data_path), delimiter=" ", dtype=np.uint32)
    X_test = raw[:, :-1].astype(np.uint8)   # feature columns
    y_test = raw[:, -1 ].astype(np.int64)   # label column

    # Hash the dataset file so anyone can verify they have the same split
    data_sha256 = hashlib.sha256(test_data_path.read_bytes()).hexdigest()

    # Run inference from the ROM (same algorithm as the RTL)
    predictions, scores = run_inference(include_matrix, X_test)

    correct      = predictions == y_test
    n_correct    = int(correct.sum())
    n_total      = len(y_test)
    accuracy_pct = round(100.0 * n_correct / n_total, 4) if n_total else 0.0

    # Per-class accuracy breakdown
    n_classes = include_matrix.shape[0]
    per_class = {{}}
    for cls in sorted(int(c) for c in np.unique(y_test)):
        cls_mask    = y_test == cls
        cls_total   = int(cls_mask.sum())
        cls_correct = int((correct & cls_mask).sum())
        per_class[str(cls)] = {{
            "correct":      cls_correct,
            "total":        cls_total,
            "accuracy_pct": round(100.0 * cls_correct / cls_total, 4) if cls_total else 0.0,
        }}

    # Confusion matrix: rows = true class, columns = predicted class
    confusion = np.zeros((n_classes, n_classes), dtype=np.int64)
    for true_cls, pred_cls in zip(y_test, predictions):
        if 0 <= int(true_cls) < n_classes and 0 <= int(pred_cls) < n_classes:
            confusion[int(true_cls), int(pred_cls)] += 1

    return {{
        "generated_at":        datetime.now(timezone.utc).isoformat(),
        "python_version":      platform.python_version(),
        "platform":            platform.platform(),
        "model_source":        model_source,
        "model_fingerprint":   meta.get("model_fingerprint", ""),
        "model_variant":       meta.get("model_variant", ""),
        "n_features":          meta.get("n_features",          include_matrix.shape[2] // 2),
        "n_classes":           meta.get("n_classes",           include_matrix.shape[0]),
        "n_clauses_total":     meta.get("n_clauses_total",     include_matrix.shape[0] * include_matrix.shape[1]),
        "n_clauses_per_class": meta.get("n_clauses_per_class", include_matrix.shape[1]),
        "hyperparameters":     meta.get("hyperparameters", {{}}),
        "provenance":          meta.get("provenance",      {{}}),
        "test_data_path":      str(test_data_path.resolve()),
        "test_data_sha256":    data_sha256,
        "n_samples":           n_total,
        "inference_engine":    "Pure NumPy — ROM-equivalent (Include-action matrix, no tmu dependency)",
        "accuracy_pct":        accuracy_pct,
        "accuracy_correct":    n_correct,
        "accuracy_total":      n_total,
        "per_class":           per_class,
        "confusion_matrix":    confusion.tolist(),
    }}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    here = Path(__file__).parent

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--model", default=str(here / "ta_actions.npy"),
        help="ta_actions.npy or tm_accelerator.v  (default: ta_actions.npy alongside this script)",
    )
    parser.add_argument(
        "--test-data", default={repr(default_test_data)},
        help="Space-separated Boolean test dataset (last column = class label)",
    )
    parser.add_argument(
        "--output", default=str(here / "provenance_report.json"),
        help="Output JSON report path  (default: provenance_report.json alongside this script)",
    )
    args = parser.parse_args()

    model_path    = Path(args.model)
    test_data_path = Path(args.test_data)
    output_path   = Path(args.output)

    if not model_path.exists():
        print(f"ERROR: model file not found: {{model_path}}", file=sys.stderr)
        sys.exit(1)
    if not test_data_path.exists():
        print(f"ERROR: test dataset not found: {{test_data_path}}", file=sys.stderr)
        sys.exit(1)

    # Step 1: load the Include-action matrix
    suffix = model_path.suffix.lower()
    if suffix == ".v":
        print(f"Step 1  Loading Include-action matrix from Verilog ROM: {{model_path.name}}")
        include_matrix, meta = load_from_verilog(model_path)
    else:
        print(f"Step 1  Loading Include-action matrix from: {{model_path.name}}")
        include_matrix, meta = load_from_npy(model_path)

    n_cls, n_cpc, n_lit = include_matrix.shape
    print(f"        {{n_cls}} classes  |  {{n_cpc}} clauses/class  |  {{n_lit//2}} features")
    print(f"        {{include_matrix.sum()}} included literals out of {{include_matrix.size}} "
          f"({{100*include_matrix.mean():.1f}}% include rate)")
    print()
    print(f"Step 2  Running inference on: {{test_data_path.name}}")

    # Steps 2+3: inference + report
    report = build_provenance_report(include_matrix, meta, test_data_path, str(model_path.resolve()))

    print(f"        Accuracy : {{report['accuracy_pct']:.2f}}%"
          f"  ({{report['accuracy_correct']}}/{{report['accuracy_total']}} correct)")
    print()
    print("        Per-class accuracy:")
    for cls, res in report["per_class"].items():
        print(f"          class {{cls:>3}}  {{res['accuracy_pct']:6.2f}}%"
              f"  ({{res['correct']}}/{{res['total']}})")
    print()
    print(f"Step 3  Provenance fingerprints")
    print(f"        Model fingerprint : {{report['model_fingerprint']}}")
    print(f"        Dataset SHA-256   : {{report['test_data_sha256']}}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, default=str))
    print()
    print(f"Report written to: {{output_path}}")


if __name__ == "__main__":
    main()
'''
