"""Write RTL/README.md for a generated bundle -- written for someone who has
never seen coal_tm and just received this directory (an RTL engineer, most
likely), not for someone already running the coal_tm CLI.

Called by both rtl.generate() (no testbench yet) and testbench.generate()
(adds the simulation section once sim/ exists), so re-running either
command keeps this file in sync with what's actually on disk instead of
the two commands independently guessing at each other's output.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from coal_tm.config import RTLConfig
from coal_tm.rtl import MODEL_SPECIFIC_SOURCES, _STATIC_TEMPLATES


def write_rtl_readme(
    rtl_dir: Path,
    config: RTLConfig,
    weight_width: int,
    n_blocks: int,
    n_vectors: int | None = None,
) -> Path:
    n_hcb_lines = n_blocks * config.clauses
    n_weight_lines = config.classes * config.clauses
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    if n_vectors is None:
        sim_section = f"""\
## Simulating this bundle

Not generated yet. From the repo this came from, run:

    coal_tm testbench --config <rtl_config.yaml> --n-vectors <N>

which adds `tb/testbench.sv`, `sim/stimulus.mem`, `sim/expected.mem`, and
two standalone scripts alongside the testbench (`tb/run_iverilog.sh`,
`tb/run_verilator.sh`) — this file gets rewritten at that point to
describe them.
"""
    else:
        sim_section = f"""\
## Simulating this bundle

This bundle includes a self-checking testbench for {n_vectors} test
vector(s) (`tb/testbench.sv`), with expected outputs computed by an
independent Python reference model (`coal_tm.emulator`) reading the same
`TAs.txt`/`weights.txt` this RTL was generated from — not copied from any
label column, so a pass is a real hardware-vs-software equivalence check,
not just "the model happened to get these examples right" (a separate,
real check — see "A note on model accuracy vs. hardware correctness"
below).

Two scripts, no Python/coal_tm required — just `iverilog`/`vvp` or
`verilator`, plus `gtkwave` to view the results:

    cd tb
    ./run_iverilog.sh     # -> tb/iverilog.vcd, prints PASS/FAIL per vector
    ./run_verilator.sh    # -> tb/verilator.vcd, same
    gtkwave tb/iverilog.vcd
    gtkwave tb/verilator.vcd

Both should print `ALL {n_vectors} VECTORS PASSED` (or something already
wrong upstream of this bundle, e.g. a corrupted TAs.txt/weights.txt export,
would show up here as a genuine per-vector `[FAIL] ... got X expected Y`
instead — see `coal_tm validate` for a model-quality check against real
labels, which is a different question from whether this RTL is correct
hardware for whatever TAs.txt/weights.txt it was given).

### A note on model accuracy vs. hardware correctness

A vector passing this testbench means the RTL computed the *same* answer
the Python reference model computes for the same input — it does **not**
mean that answer is the *correct* digit/class. A poorly-trained model can
pass every vector here (RTL faithfully reproducing its mistakes) while
still being wrong about the real world. Model quality is `coal_tm
validate`'s job (checks predictions against real labels); this testbench's
job is only "does the hardware match the software," which is what an RTL
engineer handed this bundle actually needs to know.
"""

    content = f"""\
# Coalesced TM — generated RTL

Auto-generated by `coal_tm generate` ({timestamp}) from a trained
Coalesced Tsetlin Machine model. This is real, model-specific hardware —
not a generic template with placeholders filled in — see "How this was
generated" below for exactly how to confirm that yourself, without
needing to trust this sentence.

## Model parameters

| Parameter | Value |
| --- | --- |
| classes | {config.classes} |
| clauses | {config.clauses} |
| features | {config.features} |
| bus_width | {config.bus_width} |
| packets per inference | {n_blocks} |
| adder_stages | {config.adder_stages} |
| weight width (bits, computed from weights.txt) | {weight_width} |
| TAs.txt source | `{config.tas}` |
| weights.txt source | `{config.weights}` |

## Files in this directory

### Model-specific — regenerated fresh for this exact model, not templates

None of these 5 files are templates with placeholders filled in — each is
computed directly from this model's own `TAs.txt`/`weights.txt`/config.
Two files are sensitive to the actual trained *values*: two models with
identical `classes`/`clauses`/`features`/`bus_width` but different
`TAs.txt`/`weights.txt` content still produce byte-different
`TM_Hard_Coded_Clause_Blocks.sv` and `hard_coded_weight.sv`. The other
three encode this model's *shape* (clause/feature/packet counts as
Verilog parameters and structural repetition), not its trained values —
they'll differ between models of different shape, but two independently
trained models that happen to share the same shape legitimately produce
identical `HCB_top.sv`/`TM_top.sv`/`axis_wrapper.sv` (there's nothing
value-specific left to encode once the shape is fixed). Both are still
"generated, not copied" — see the checks below.

| File | Sensitive to | What's actually in it |
| --- | --- | --- |
| `TM_Hard_Coded_Clause_Blocks.sv` | **trained values** (`TAs.txt`) | {n_blocks} `HCB_*` module(s), one per {config.bus_width}-feature-wide packet; each clause's Verilog AND-expression is this model's own Include-literal pattern, thresholded at automaton state ≥ 128. {n_hcb_lines} `partial_clause[...]` assignment lines total ({n_blocks} blocks × {config.clauses} clauses). |
| `hard_coded_weight.sv` | **trained values** (`weights.txt`) | This model's actual signed integer weights, baked as `{n_weight_lines}` (= {config.classes} classes × {config.clauses} clauses) `assign weights[c][j] = <value>'b<bits>;` lines in two's complement. |
| `HCB_top.sv` | model shape only | Chains the `HCB_*` modules above; {n_blocks} `HCB_inst_*` instantiations, dispatch logic sized to `PACKETS_NUM={n_blocks}`. |
| `TM_top.sv` | model shape only | Top-level pipeline; `CLAUSE_NUM`/`WEIGHT_LENGTH` parameters sized for this model ({config.clauses}, {weight_width}). |
| `axis_wrapper.sv` | model shape only | AXI-Stream wrapper; `FEATURE_NUM`/`PACKETS_NUM` sized for this model ({config.features}, {n_blocks}). |

**Verify it yourself** (no coal_tm/Python needed, just grep/wc):

    grep -c "assign weights\\[" hard_coded_weight.sv              # expect {n_weight_lines}
    grep -c "partial_clause\\[" TM_Hard_Coded_Clause_Blocks.sv    # expect {n_hcb_lines}
    grep -c "HCB_inst_[0-9]\\+(" HCB_top.sv                       # expect {n_blocks}

If you have RTL generated from a *different* trained model, `diff` it
against this directory: `TM_Hard_Coded_Clause_Blocks.sv` (different clause
logic) and `hard_coded_weight.sv` (different weight constants) will
differ regardless of shape; `HCB_top.sv`/`TM_top.sv`/`axis_wrapper.sv`
will differ too if the model's shape also differs, or match if it
doesn't (see the table above); the 3 static files below will always
match either way.

### Static IP — byte-identical every time, copied verbatim

Not regenerated per model; these implement fixed, model-independent
logic (the AXI-Stream slave/master shim, the weighted-sum adder tree,
and the argmax/output-framing logic) and are copied unmodified from this
repo's `utils/RTL_templates/` on every `coal_tm generate` run.

{chr(10).join(f"- `{name}`" for name in _STATIC_TEMPLATES)}

## How this was generated

`coal_tm generate` (`coal_tm/rtl.py`):
1. Reads `TAs.txt` (raw Tsetlin Automaton states, one per literal per
   clause) and thresholds each at automaton state ≥ 128 to get an
   Include/Exclude bit per literal (`coal_tm/artifacts.py`).
2. Reads `weights.txt` (flat, signed integers, row-major by class) into a
   `(classes, clauses)` matrix.
3. For each `{config.bus_width}`-feature-wide packet, emits one `HCB_*`
   module whose `{config.clauses}` clause expressions are literally
   `x[i]`/`~x[i]` ANDed together for whatever literals that clause
   Includes in that packet's feature range — a clause with zero Included
   literals anywhere is forced to constant `0` (matching TMU's own
   reference semantics: an empty clause never fires), not left as a
   trivially-true placeholder.
4. Emits `hard_coded_weight.sv` with this model's actual weight values,
   in two's complement, at a bit width computed to hold the largest
   weight magnitude *and* the worst-case accumulated class sum without
   overflow (`coal_tm.rtl._weight_width`) — the same width used for
   `WEIGHT_LENGTH` everywhere else in the design, so there's no risk of
   two independently-sized widths silently disagreeing.
5. Copies the 3 static files above unmodified.

{sim_section}
---
Regenerate this file (and the rest of this directory) with
`coal_tm generate --config <rtl_config.yaml>`.
"""

    readme_path = rtl_dir / "README.md"
    readme_path.write_text(content)
    return readme_path
