"""Generate a self-checking testbench.sv plus stimulus/expected files for a
Coalesced-TM RTL bundle, sized from real config instead of hand-tuned magic
numbers (the old write_testbench()/pack_data() hardcoded DATAPOINTS=10 and an
unexplained `input_counter == 160` cutoff), with expected outputs computed by
coal_tm.emulator — not copied from the test data's label column, which only
"validates" the hardware if the model happens to get those examples right.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from coal_tm.config import RTLConfig
from coal_tm.emulator import CoalescedEmulator


@dataclass
class TestbenchArtifacts:
    testbench_path: Path
    stimulus_path: Path
    expected_path: Path
    n_vectors: int
    n_blocks: int


def _load_vectors(test_data: Path, features: int, n_vectors: int) -> np.ndarray:
    raw = np.loadtxt(test_data, dtype=int, ndmin=2)
    X = raw[:, :-1]
    if X.shape[1] != features:
        raise ValueError(f"{test_data} has {X.shape[1]} feature columns, expected {features}")
    if X.shape[0] < n_vectors:
        raise ValueError(f"{test_data} has only {X.shape[0]} rows, need {n_vectors}")
    return X[:n_vectors]


def _pack_stimulus(path: Path, X: np.ndarray, bus_width: int) -> int:
    """One $readmemb-compatible binary-digit line per packet. Bit-reversed
    (MSB-first) within each packet: $readmemb assigns a string's first
    character to a vector's MSB, so local feature index 0 (the bit
    coal_tm.rtl's HCB blocks call x[0]) must be the string's *last*
    character to land in x[0] after $readmemb. Returns packets-per-vector.
    """
    n_vectors, features = X.shape
    n_blocks = math.ceil(features / bus_width)
    with open(path, "w") as f:
        for row in X:
            for b in range(n_blocks):
                block = row[b * bus_width:(b + 1) * bus_width]
                if block.shape[0] < bus_width:
                    pad = np.zeros(bus_width - block.shape[0], dtype=block.dtype)
                    block = np.concatenate([block, pad])
                bits = "".join(str(int(v)) for v in reversed(block.tolist()))
                f.write(bits + "\n")
    return n_blocks


def _write_expected(path: Path, predictions: np.ndarray) -> None:
    """One $readmemh-compatible hex line per vector."""
    with open(path, "w") as f:
        for p in predictions:
            f.write(format(int(p), "x") + "\n")


def _write_testbench_sv(
    path: Path,
    stimulus_path: Path,
    expected_path: Path,
    bus_width: int,
    n_vectors: int,
    n_blocks: int,
    clauses: int,
    classes: int,
    features: int,
    weight_width: int,
) -> None:
    n_packets = n_vectors * n_blocks
    with open(path, "w") as f:
        print(
            f"""\
`timescale 1ns/1ps
// Auto-generated by coal_tm.testbench. Drives {n_vectors} test vector(s)
// ({n_packets} AXI-Stream packet(s) total) through the generated Coalesced
// TM core and checks every predicted class against coal_tm.emulator's
// prediction for the same TAs.txt/weights.txt — not the test data's own
// label column, so this is a real hardware-vs-software equivalence check,
// not just "did the model happen to get these examples right".

module testbench;
    localparam CLK_PERIOD = 10;
    localparam BUS_WIDTH  = {bus_width};
    localparam N_VECTORS  = {n_vectors};
    localparam N_PACKETS  = {n_packets};

    reg clk = 0;
    reg aresetn = 0;
    reg [BUS_WIDTH-1:0] stimulus [0:N_PACKETS-1];
    reg [31:0] expected [0:N_VECTORS-1];

    reg s00_tvalid = 0;
    reg s00_tlast = 0;
    reg [BUS_WIDTH-1:0] s00_tdata = 0;
    wire s00_tready;

    reg m00_tready = 1;
    wire m00_tvalid;
    wire m00_tlast;
    wire [BUS_WIDTH-1:0] m00_tdata;

    integer packet_idx;
    integer received = 0;
    integer failures = 0;

    axis_wrapper_top #(
        .PACKETS({n_blocks}),
        .C_S00_AXIS_TDATA_WIDTH({bus_width}),
        .C_M00_AXIS_TDATA_WIDTH({bus_width}),
        .STAGE_NUM(1),
        .CLAUSE_NUM({clauses}),
        .CLASS_NUM({classes}),
        .WEIGHT_LENGTH({weight_width}),
        .FEATURE_NUM({features}),
        .PACKETS_NUM({n_blocks})
    ) dut (
        .s00_axis_aclk(clk),
        .s00_axis_aresetn(aresetn),
        .s00_axis_tdata(s00_tdata),
        .s00_axis_tstrb('1),
        .s00_axis_tlast(s00_tlast),
        .s00_axis_tvalid(s00_tvalid),
        .s00_axis_tready(s00_tready),
        .m00_axis_aclk(clk),
        .m00_axis_aresetn(aresetn),
        .m00_axis_tready(m00_tready),
        .m00_axis_tvalid(m00_tvalid),
        .m00_axis_tdata(m00_tdata),
        .m00_axis_tlast(m00_tlast)
    );

    always #(CLK_PERIOD/2) clk = ~clk;

    initial begin
        $readmemb("{stimulus_path.name}", stimulus);
        $readmemh("{expected_path.name}", expected);
    end

    // Non-blocking assignment throughout: this process is triggered by the
    // same @(posedge clk) the DUT's own registers react to, so a blocking
    // assignment here would race the DUT's same-edge sampling of these
    // signals (whichever process the simulator happens to schedule first
    // on a given edge wins -- Icarus Verilog resolved that race the same,
    // consistently wrong way every time, silently skipping every other
    // packet's worth of data into a stale, already-superseded value).
    // Non-blocking guarantees the DUT always sees the value this signal
    // held throughout the *previous* full cycle, never one still changing
    // on the edge being sampled.
    initial begin
        aresetn <= 0;
        s00_tvalid <= 0;
        repeat (4) @(posedge clk);
        aresetn <= 1;
        @(posedge clk);

        for (packet_idx = 0; packet_idx < N_PACKETS; packet_idx = packet_idx + 1) begin
            s00_tdata  <= stimulus[packet_idx];
            s00_tvalid <= 1;
            s00_tlast  <= (packet_idx == N_PACKETS - 1);
            @(posedge clk);
            // Hold this packet on the bus until the DUT actually accepts it
            // (s00_tready high) -- the DUT deasserts tready while a
            // previous inference is still draining through the argmax
            // pipeline (see Hard_Coded_Inference_Top's busy_countdown).
            // Without waiting here, a new vector's first packet could be
            // presented and silently missed while the DUT is still busy.
            while (!s00_tready) begin
                @(posedge clk);
            end
        end
        s00_tvalid <= 0;
        s00_tlast  <= 0;
    end

    // Sample on the negative edge, well after the posedge-triggered blocking
    // assignments inside the DUT's classify block (which intentionally
    // chain same-cycle reads of values it just wrote) have fully settled --
    // a fixed #1 delay after posedge isn't reliably enough, and simulators
    // differ on exactly when such chains resolve within one timestep.
    always @(negedge clk) begin
        if (m00_tvalid && m00_tready) begin
            if (m00_tdata !== expected[received]) begin
                $display("[FAIL] vector %0d: got %0d expected %0d", received, m00_tdata, expected[received]);
                failures = failures + 1;
            end
            else begin
                $display("[PASS] vector %0d: class %0d", received, m00_tdata);
            end
            received = received + 1;
            if (received == N_VECTORS) begin
                if (failures == 0)
                    $display("ALL %0d VECTORS PASSED", N_VECTORS);
                else
                    $display("%0d OF %0d VECTORS FAILED", failures, N_VECTORS);
                $finish;
            end
        end
    end

    initial begin
        #(CLK_PERIOD * (N_PACKETS * 20 + 10000));
        $display("TIMEOUT: only received %0d of %0d predictions", received, N_VECTORS);
        $finish;
    end

endmodule
""",
            file=f,
        )


def generate(config: RTLConfig, n_vectors: int, test_data: Path | None = None) -> TestbenchArtifacts:
    test_data = test_data or config.test_data
    if test_data is None:
        raise ValueError("no test_data given (neither the --test-data flag nor config.test_data)")

    X = _load_vectors(test_data, config.features, n_vectors)

    emu = CoalescedEmulator(config.tas, config.weights, config.classes, config.clauses, config.features)
    predictions, _ = emu.predict_batch(X)

    rtl_dir = config.output_dir / "RTL"
    sim_dir = rtl_dir / "sim"
    tb_dir = rtl_dir / "tb"
    sim_dir.mkdir(parents=True, exist_ok=True)
    tb_dir.mkdir(parents=True, exist_ok=True)

    stimulus_path = sim_dir / "stimulus.mem"
    n_blocks = _pack_stimulus(stimulus_path, X, config.bus_width)

    expected_path = sim_dir / "expected.mem"
    _write_expected(expected_path, predictions)

    weights = np.loadtxt(config.weights, dtype=int)
    from coal_tm.rtl import _weight_width  # single source of truth, see coal_tm.rtl
    width = _weight_width(weights, config.clauses)

    testbench_path = tb_dir / "testbench.sv"
    _write_testbench_sv(
        testbench_path, stimulus_path, expected_path, config.bus_width, n_vectors, n_blocks,
        config.clauses, config.classes, config.features, width,
    )

    return TestbenchArtifacts(
        testbench_path=testbench_path, stimulus_path=stimulus_path,
        expected_path=expected_path, n_vectors=n_vectors, n_blocks=n_blocks,
    )
